// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  userManualSidebar: [{type: 'autogenerated', dirName: 'visren/user-manual'}],
  progGuideSidebar: [{type: 'autogenerated', dirName: 'visren/prog-guide'}],
  importersSidebar: [{type: 'autogenerated', dirName: 'importers'}],
  maxExporterSidebar: [{type: 'autogenerated', dirName: 'misc/max-exporter'}],
};

export default sidebars;
