import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  
  // User Manuals
  importersAndExportersSidebar: [{
    type: 'category',
    label: 'Importers and Exporters',
    items: [{ type: 'autogenerated', dirName: 'importers-and-exporters' }],
    collapsed: false,
  }],

  licenseServerSidebar: [{
    type: 'category',
    label: 'License Server',
    items: [{ type: 'autogenerated', dirName: 'license-server' }],
    collapsed: false,
  }],

  virtalisHubAndWebViewerSidebar: [{
    type: 'category',
    label: 'Virtalis Hub and Web Viewer',
    items: [{ type: 'autogenerated', dirName: 'virtalis-hub-and-web-viewer' }],
    collapsed: false,
  }],

  visionaryRenderSidebar: [{
    type: 'category',
    label: 'Visionary Render',
    items: [{ type: 'autogenerated', dirName: 'visionary-render' }],
    collapsed: false,
  }],

  // Technical Guides
  virtalisHubSystemAdminSidebar: [{
    type: 'category',
    label: 'Virtalis Hub System Admin',
    items: [{ type: 'autogenerated', dirName: 'virtalis-hub-system-admin' }],
    collapsed: false,
  }],

  visionaryRenderProgrammingSidebar: [{
    type: 'category',
    label: 'Visionary Render Programming',
    items: [{ type: 'autogenerated', dirName: 'visionary-render-programming' }],
    collapsed: false,
  }],

  // Release Notes
  releaseNotesSidebar: [{
    type: 'category',
    label: 'Release Notes',
    link: { type: 'generated-index', slug: 'release-notes' },
    items: [{ type: 'autogenerated', dirName: 'release-notes' }],
    collapsed: false,
  }],

  // Changelogs
  changelogsSidebar: [{
    type: 'category',
    label: 'Changelogs',
    link: { type: 'generated-index', slug: 'changelogs' },
    items: [{ type: 'autogenerated', dirName: 'changelogs' }],
    collapsed: false,
  }],
};

export default sidebars;
